import { generateObject } from 'ai';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import { aiExtractionResponseSchema } from '../schemas/crm.schema';

const google = createGoogleGenerativeAI({
  apiKey: process.env.GEMINI_API_KEY,
});

export async function extractRecordsWithGemini(recordsBatch: Record<string, unknown>[]): Promise<Record<string, unknown>[]> {
  if (process.env.AI_MOCK_MODE === 'true') {
    // Network delay simulation (1000ms - 2000ms)
    const delay = Math.floor(Math.random() * 1000) + 1000;
    await new Promise((resolve) => setTimeout(resolve, delay));
    
    // Deterministic mock mapping
    return recordsBatch.map((record) => {
      // Helper: pick first truthy value from a list of candidate keys (case-insensitive key lookup)
      const pick = (...keys: string[]): string => {
        for (const key of keys) {
          // Exact match first
          if (record[key] !== undefined && record[key] !== null && record[key] !== '') {
            return String(record[key]);
          }
          // Case-insensitive fallback
          const lower = key.toLowerCase();
          const found = Object.entries(record).find(([k]) => k.toLowerCase() === lower);
          if (found && found[1] !== undefined && found[1] !== null && found[1] !== '') {
            return String(found[1]);
          }
        }
        return '';
      };

      return {
        name: pick('First Name', 'Name', 'Full Name', 'Lead Full Name', 'name'),
        email: pick('Email', 'Contact Mail', 'Email Address', 'email'),
        country_code: pick('Country Code', 'country_code') || '+91',
        mobile_without_country_code: pick(
          'Mobile', 'Phone', 'Contact Numbers', 'Contact Number',
          'WhatsApp No', 'WhatsApp', 'Mobile No', 'Phone Number',
          'mobile', 'mobile_without_country_code'
        ),
        company: pick('Organization', 'Organisation', 'Company', 'company'),
        city: pick('City', 'Location', 'city'),
        state: pick('State', 'state'),
        country: pick('Country', 'country') || 'India',
        lead_owner: pick('Assigned To', 'Sales Person', 'Lead Owner', 'lead_owner'),
        crm_status: 'GOOD_LEAD_FOLLOW_UP',
        crm_note: pick('Remarks', 'Notes', 'Comment', 'crm_note') || 'Generated by AI Mock Mode',
        data_source: pick('Campaign', 'Source', 'data_source') || 'leads_on_demand',
        possession_time: pick('Possession Time', 'possession_time'),
        description: pick('Description', 'Project', 'description'),
        // Preserve source date — try common column names; do NOT fall back to current timestamp
        created_at: pick('created_at', 'Created On', 'Date Created', 'Date', 'Creation Date', 'Timestamp'),
      };
    });
  }

  const prompt = `
You are an expert data migration assistant. Your task is to extract, normalize, and map an array of arbitrary CSV rows into a strict CRM schema.
The user will provide an array of JSON objects representing the raw CSV rows. 

CRITICAL INSTRUCTIONS:
1. You must return exactly one output record for every input record in the same order.
2. Maintain all fields exactly as defined in the schema. Do not add new fields.
3. If an input field is missing, ambiguous, or cannot be confidently mapped, output an empty string "".
4. CRM STATUS VALIDATION: Only use 'GOOD_LEAD_FOLLOW_UP', 'DID_NOT_CONNECT', 'BAD_LEAD', 'SALE_DONE'. If nothing matches, use "".
5. DATA SOURCE VALIDATION: Only use 'leads_on_demand', 'meridian_tower', 'eden_park', 'varah_swamy', 'sarjapur_plots'. If nothing matches confidently, use "".
6. DATE HANDLING: 'created_at' must be a valid parsable date string or "". Do not invent dates.
7. EMAILS/MOBILES: If multiple emails exist, put the first in 'email' and remaining in 'crm_note'. If multiple mobiles exist, put the first in 'mobile_without_country_code' and remaining in 'crm_note'. Extract country code to 'country_code'.
8. CRM NOTE: Use this for remarks, follow-up notes, comments, additional contact info, and miscellaneous useful data. Format clearly.

Input Batch:
${JSON.stringify(recordsBatch, null, 2)}
  `;

  try {
    const { object } = await generateObject({
      model: google('gemini-2.5-flash'),
      schema: aiExtractionResponseSchema,
      prompt: prompt,
      temperature: 0.1,
    });

    return object.records;
  } catch (error) {
    console.error('Gemini extraction failed:', error);
    throw error;
  }
}
